### ISSUE TITLE
Event: onMessageReceived

### ISSUE THREAD

**Issue by umutcoskun** [alamin-karno/flutter-crisp-chat#17]
**Problem:** If users receives a message while the chat box is closed, they will never notice the message agent sent, until they click and open the chat box again.

Can be something like:
```
CrispConfig(
    websiteID: 'xxxx-xxxx-xxxx-xxxx',
    user: User(),
    onMessageReceived: (message) {
        FlutterCrispChat.showChatBox();
    }
),
```

**Comment by alamin-karno** [comment]
Hi @umutcoskun and thank you for your feedback.

For the moment, this feature is not implemented.

As discussed in [#169](https://github.com/crisp-im/crisp-sdk-android/issues/169#issuecomment-2018376805) and [#172](https://github.com/crisp-im/crisp-sdk-android/issues/172), the socket is only maintained when the `ChatActivity` is running so not before starting it, not after and not in app background, only in foreground, so if stopped, the Crisp SDK is not able to know if a new message has been received until the `ChatActivity` is restart.

This is clearly a limitation of Crisp SDK current implementation by design.
As said in this same comment, they're discussing internally about it but it's not their main priority currently.
